config/routes.rb
Rails.application.routes.draw do
  root 'users#top'
  get '/about' => 'users#about', as: 'about'
  get '/article/:id/histories' => 'article_histories#index', as: 'article_histories'
  get '/article_histories/:id' => 'article_histories#show', as: 'article_history'
  get '/stories/convert' => 'stories#markdown_convertion', as: 'convert_story'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only:[:show, :index, :edit, :update]
  resources :articles, only:[:show, :index, :new, :edit, :create, :update, :destroy] do
    resource :stories, only:[:new, :create, :destroy]
    resource :article_comments, only:[:create]
  end
  resources :stories, only:[:show, :new, :edit, :create, :update, :destroy] do
    resource :libraries, only:[:create, :destroy]
    resource :story_comments, only:[:create]
  end
  resources :story_comments, only:[:destroy]
  resources :article_comments, only:[:destroy]
  resources :categories, only:[:show]
  resources :libraries, only:[:index, :create, :destroy]

  get 'users/:id/admin' => 'users#admin_show', as: 'admin_user'
  get 'admin/cmd' => 'users#admin_command', as: 'admin_cmd'
  get 'comments/' => 'users#admin_comments', as: 'admin_comments'
  patch 'users/d/:id' => 'users#unsubscribe', as: 'unsubscribe_user'
  patch 'articles/ow/:id' => 'article_histories#overwrite', as: 'overwrite_article'
  delete 'article_comments/:id/admin' => 'article_comments#destroy_from_admin_page', as: 'admin_destroies_article_comment'
  delete 'story_comments/:id/admin' => 'story_comments#destroy_from_admin_page', as: 'admin_destroies_story_comment'
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  has_many :article_comments, dependent: :destroy
  has_many :stories
  has_many :article_histories, dependent: :destroy

  validates :title, presence: true, length:{maximum: 75}
  validates :mean, presence: true
  validates :cause, presence: true

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  def save_article_categories(tags)
    current_tags = self.categories.pluck(:name) unless self.categories.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.categories.delete Category.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      article_category = Category.find_or_create_by(name:new_name)
      self.categories << article_category
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update]
  def new
    @article = Article.new
  end

  def index
    @articles = Article.order(:created_at).reverse_order.page(params[:page]).per(10).search(params[:search])
    @stories = Story.order(:created_at).reverse_order.page(params[:page]).per(10).search(params[:search])
    return unless request.xhr?
    case params[:type]
    when 'article'
      render "/articles/article_list"
    when 'story'
      render "/stories/story_list"
    end
  end

  def show
    @article = Article.find(params[:id])
    @stories = @article.stories.order(:created_at).reverse_order.page(params[:page]).per(10)
    @article_comments = @article.article_comments.reverse
    @article_comment = ArticleComment.new
    @admin_comment_page = false
  end

  def edit
    @article = Article.find(params[:id])
    @category_list = @article.categories.pluck(:name).join(",")
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    category_list = params[:category_list].split(",")
    if @article.save
      @article.save_article_categories(category_list)
      redirect_to article_path(@article), notice: 'エラー記事を作成しました。'
    else
      flash.now[:alert] = 'エラー記事の作成に失敗しました'
      render :new
    end
  end

  def update
    @article = Article.find(params[:id])
    @article.user_id = current_user.id
    @old_article = @article
    if @article.update(article_params)
      create_article_history(@old_article)
      category_list = params[:category_list].split(",")
      @article.save_article_categories(category_list)
      redirect_to article_path(@article), notice: 'エラー記事を更新しました。'
    else
      flash.now[:alert] = 'エラー記事の更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      redirect_to articles_path, notice: 'ストーリーを削除しました'
    else
      @category_list = params[:category_list].split(",")
      flash.now[:alert] = 'ストーリーの更新に失敗しました。'
      render :edit
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :mean, :cause)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_list.html.erb
<% articles.each do |article| %>
  <div class="content-list clearfix">
    <h4><%= link_to article.title, article_path(article) %></h4>
    <p><%= daytime_localize(article.updated_at) %></p>
  </div>
<% end %>

app/views/articles/_article_lists_wrapper.html.erb
<div id="articles">
  <%= render partial: '/articles/article_list', locals:{articles: articles} %>
</div>
<% if articles.next_page %>
  <div id="more-article-link">
    <%= link_to_next_page articles, 'さらに10件表示', params: { type: :article }, remote: true, id:"more-articles" %>
  </div>
<% end %>

app/views/articles/article_list.js.erb
$('#more-articles').remove();
$('#articles').append("<%= j render partial: '/articles/article_list', locals:{articles: @articles} %>");
$('#more-article-link').append("<%= j link_to_next_page @articles, 'さらに10件表示', params: { type: :article }, remote: true, id: 'more-articles' %>")
$('#loading').css('display', 'none');
$('#more-articles').click(function(){
  $('#loading').css('display', 'table');
});

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div id="content-left" class="content-area col-md-12 col-xs-12">
      <div class ="content-box">
        <h2 class="content-box-head">項目の編集</h2>
        <%= form_for(@article) do |f| %>
          <div class="content-box-body">
            <%= render '/layouts/validation_error', model: f.object %>
            <h5>エラー名：
            <%= f.text_field :title, placeholder: "エラー名を入力", class:'title-field' %></h5>
            <div class="tag-list">
              タグ：
                <ul id="article-tags">
                </ul>
                <%= hidden_field_tag :category_hidden,@category_list %>
            </div>
            <h5>- 意味</h5>
            <%= f.text_area :mean, class:"body-textarea" %>
            <h5>- 原因</h5>
            <%= f.text_area :cause, class:"body-textarea" %>
            <% if admin? %>
              <%= link_to "エラー情報の削除", article_path(@article), method: :delete, data:{confirm: "削除は十分なディスカッションを行ってから実行してください。本当に削除しますか？"}, class:"btn btn-danger" %>
            <% end %>
          </div>
          <div class="content-box-foot">
            <%= link_to "戻る", article_path(@article), class: "btn btn-half btn-sub2" %>
            <%= f.submit "保存", class: "btn btn-half btn-sub" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container" >
  <div class="row">
   <div id="content-left" class="content-area col-md-6 col-xs-12">
      <div class ="content-box">
        <h2 class="content-box-head">検索結果(エラー)</h2>
        <div class="content-box-body">
          <%= render '/articles/article_lists_wrapper', articles: @articles %>
        </div>
        <div class="content-box-foot">
          <% if user_signed_in? %>
            <div>
              <%= link_to 'エラー記事の作成' ,new_article_path, class:'btn btn-sub'%>
            </div>
          <% else %>
            <p class="foot-not-active">
              エラー記事の作成(ログイン時のみ)
            </p>
          <% end %>
        </div>
      </div>
    </div>

    <div id="content-right" class="content-area col-md-6 col-xs-12">
      <div class ="content-box">
        <h2 class ="content-box-head">検索結果(ストーリー)</h2>
        <div class="content-box-body">
          <%= render '/stories/story_lists_wrapper', stories: @stories %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div id="content-left" class="content-area col-md-12 col-xs-12">
      <div class ="content-box">
        <h2 class="content-box-head">項目の追加</h2>
        <%= form_for(@article) do |f| %>
          <div class="content-box-body">
            <%= render '/layouts/validation_error', model: f.object %>
            <h4><%= f.text_field :title, placeholder: "エラー名を入力", class:'title-field' %></h4>
            <div class="tag-list">
              タグ：
                <ul id="article-tags">
                </ul>
            </div>
            <h4>- 意味</h4>
            <%= f.text_area :mean, class:"body-textarea" %>
            <h4>- 原因</h4>
            <%= f.text_area :cause, class:"body-textarea" %>
          </div>
          <div class="content-box-foot">
            <div>
              <%= link_to "戻る", articles_path, class: "btn btn-half btn-sub2" %><%= f.submit "保存", class: "btn btn-half btn-sub" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">

    <div id="content-left" class="content-area col-md-6 col-xs-12">
      <div id="main-content" class ="content-box">
        <h2 class="content-box-head"><%= @article.title %></h2>
        <div class="content-box-body">
          <p>タグ：
            <% @article.categories.each do |category| %>
              <%= link_to category.name, category_path(category), class: 'category-tag' %>
            <% end %>
          </p>
          <h4>● 意味</h4>
          <div class="article-body-area">
            <%= simple_format(@article.mean) %>
          </div>
          <h4>● 主な原因</h4>
          <div class="article-body-area">
            <%= simple_format(@article.cause) %>
          </div>
        </div>
        <div class="content-box-foot">
          <% if user_signed_in? %>
          <div class="clearfix">
            <%= link_to "エラー情報の編集", edit_article_path(@article), class:"btn btn-half" %>
            <div id="sub-content-show" class="btn btn-sub2 btn-half">ディスカッション</div>
          </div>
          <% end %>
          <% if admin? %>
          <!-- 管理者ログイン時 -->
          <p>
            最終更新：<%= link_to daytime_localize(@article.updated_at), article_histories_path %>
          </p>
          <% else %>
          <!-- 利用者ログイン時 -->
          <p>
            最終更新：<%= daytime_localize(@article.updated_at) %>
          </p>
          <% end %>
        </div>
      </div>

      <div id="sub-content" class ="content-box">
        <h2 class ="content-box-head">ディスカッション</h2>
        <div class="content-box-body">
          <p id="sub-content-hide" class="btn btn-sub2">ディスカッションを終了する</p>
          <div id="article-comment-lists">
            <%= render partial: '/article_comments/comments', locals:{article_comments: @article_comments, admin_comment_page: @admin_comment_page} %>
          </div>
        </div>
        <div class="content-box-foot">
          <div id="comment-flash">
            <%= render partial: '/layouts/flash', locals:{flash: flash} %>
          </div>
          <div id="comment-post-field">
            <%= render partial: 'layouts/post_comment', locals:{parent: @article, parent_comment: @article_comment} %>
          </div>
        </div>
      </div>
    </div>

    <div id="content-right" class="content-area col-md-6 col-xs-12">
      <div class ="content-box">
        <h2 class ="content-box-head">関連ストーリー</h2>
        <div class="content-box-body">
          <%= render '/stories/story_lists_wrapper', stories: @stories %>
        </div>
        <div class="content-box-foot">
          <% if user_signed_in? %>
            <div>
              <%= link_to 'ストーリーの作成', new_article_stories_path(@article), class:'btn' %>
            </div>
          <% else %>
            <p class="foot-not-active">
              ストーリーの作成(ログイン時のみ)
            </p>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>