config/routes.rb
Rails.application.routes.draw do
  root 'users#top'
  get '/about' => 'users#about', as: 'about'
  get '/article/:id/histories' => 'article_histories#index', as: 'article_histories'
  get '/article_histories/:id' => 'article_histories#show', as: 'article_history'
  get '/stories/convert' => 'stories#markdown_convertion', as: 'convert_story'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only:[:show, :index, :edit, :update]
  resources :articles, only:[:show, :index, :new, :edit, :create, :update, :destroy] do
    resource :stories, only:[:new, :create, :destroy]
    resource :article_comments, only:[:create]
  end
  resources :stories, only:[:show, :new, :edit, :create, :update, :destroy] do
    resource :libraries, only:[:create, :destroy]
    resource :story_comments, only:[:create]
  end
  resources :story_comments, only:[:destroy]
  resources :article_comments, only:[:destroy]
  resources :categories, only:[:show]
  resources :libraries, only:[:index, :create, :destroy]

  get 'users/:id/admin' => 'users#admin_show', as: 'admin_user'
  get 'admin/cmd' => 'users#admin_command', as: 'admin_cmd'
  get 'comments/' => 'users#admin_comments', as: 'admin_comments'
  patch 'users/d/:id' => 'users#unsubscribe', as: 'unsubscribe_user'
  patch 'articles/ow/:id' => 'article_histories#overwrite', as: 'overwrite_article'
  delete 'article_comments/:id/admin' => 'article_comments#destroy_from_admin_page', as: 'admin_destroies_article_comment'
  delete 'story_comments/:id/admin' => 'story_comments#destroy_from_admin_page', as: 'admin_destroies_story_comment'
end

app/models/story_comment.rb
class StoryComment < ApplicationRecord
  belongs_to :user
  belongs_to :story

  validates :comment, presence: true

  def self.search(search)
    if search
      where(['comment LIKE ?', "%#{search}%"])
    else
      all
    end
  end

end

app/controllers/story_comments_controller.rb
class StoryCommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @story = Story.find(params[:story_id])
    @story_comment = @story.story_comments.new(story_comment_params)
    @story_comment.user_id = current_user.id
    @story_comments = @story.story_comments.reverse
    respond_to do |format|
      if @story_comment.save
        @story_comment = StoryComment.new
        @story_comments = @story.story_comments.reverse
        format.js { flash.now[:success] = "トークルームへ投稿しました。" }
      else
        flash.now[:alert] = "投稿に失敗しました。"
        format.js { render 'error' }
      end
    end
  end

  def destroy
    @story_comment = StoryComment.find(params[:id])
    @story = Story.find(@story_comment.story_id)
    respond_to do |format|
      if @story_comment.destroy
        @story_comments = @story.story_comments.reverse
        format.html
        format.js { flash.now[:success] = "投稿を削除しました。" }
      else
        flash.now[:alert] = "投稿の削除に失敗しました。"
        format.html
        format.js { render 'error'}
      end
    end
  end

  def destroy_from_admin_page
    @story_comment = StoryComment.find(params[:id])
    respond_to do |format|
      if @story_comment.destroy
        @story_comments = StoryComment.all.reverse
        format.html
        format.js { flash.now[:success] = "投稿を削除しました。" }
      else
        flash.now[:alert] = "投稿の削除に失敗しました。"
        format.html
        format.js { render 'error'}
      end
    end
  end

  private

  def story_comment_params
    params.require(:story_comment).permit(:story_id, :user_id, :comment)
  end

end

app/helpers/story_comments_helper.rb
module StoryCommentsHelper
end

app/views/story_comments/_comments.html.erb
<% if story_comments.count == 0 %>
  <div class="content-list clearfix">
    <p>まだ投稿はありません。</p>
  </div>
<% else %>
  <% story_comments.each do |comment| %>
    <% if comment.user.deleted_user == false %>
      <div class="comment-list clearfix">
        <%= attachment_image_tag comment.user, :image, size: '64x64', class: 'comment-user-thumb' %>
        <div class="comment-user-text">
          <p class="comment-user-name">
          <% if comment.user.admin == true %>
            <%= comment.user.name %>
          <% else %>
            <%= link_to comment.user.name, user_path(comment.user) %>
          <% end %>
          </p>
          <p><%= simple_format(comment.comment) %></p>
          <p><%= daytime_localize(comment.updated_at) %>
            <% if @admin_comment_page %>
              <span>
                / <%= link_to "削除", admin_destroies_story_comment_path(comment), method: :delete, remote: true, data: { confirm: '削除してもよろしいですか？' } %>
              </span>
            <% elsif same_user_or_admin?(comment.user) %>
              <span>
                / <%= link_to "削除", story_comment_path(comment), method: :delete, remote: true, data: { confirm: '削除してもよろしいですか？' } %>
              </span>
            <% end %>
           </p>
           <% if admin? %>
              <p>(リソース：<%= link_to comment.story.title, story_path(comment.story) %>)</p>
            <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/story_comments/create.js.erb
$('#story-comment-lists').html("<%= j(render partial: '/story_comments/comments', locals:{story_comments: @story_comments}) %>");
$('#comment-flash').html("<%= j(render partial: '/layouts/flash', locals:{flash: flash}) %>");
$('#comment-post-field').html("<%= j(render partial: 'layouts/post_comment', locals:{parent: @story, parent_comment: @story_comment}) %>");
$(function(){
  setTimeout(function(){
  $('#flash').fadeOut()}, 3000)
});

app/views/story_comments/destroy.js.erb
$('#story-comment-lists').html("<%= j(render partial: '/story_comments/comments', locals:{story_comments: @story_comments}) %>");
$('#comment-flash').html("<%= j(render partial: '/layouts/flash', locals:{flash: flash}) %>");
$(function(){
  setTimeout(function(){
  $('#flash').fadeOut()}, 3000)
});

app/views/story_comments/destroy_from_admin_page.js.erb
$('#story-comment-lists').html("<%= j(render partial: '/story_comments/comments', locals:{story_comments: @story_comments}) %>");
$('#comment-flash').html("<%= j(render partial: '/layouts/flash', locals:{flash: flash}) %>");
$(function(){
  setTimeout(function(){
  $('#flash').fadeOut()}, 3000)
});