config/routes.rb
Rails.application.routes.draw do
  root 'users#top'
  get '/about' => 'users#about', as: 'about'
  get '/article/:id/histories' => 'article_histories#index', as: 'article_histories'
  get '/article_histories/:id' => 'article_histories#show', as: 'article_history'
  get '/stories/convert' => 'stories#markdown_convertion', as: 'convert_story'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only:[:show, :index, :edit, :update]
  resources :articles, only:[:show, :index, :new, :edit, :create, :update, :destroy] do
    resource :stories, only:[:new, :create, :destroy]
    resource :article_comments, only:[:create]
  end
  resources :stories, only:[:show, :new, :edit, :create, :update, :destroy] do
    resource :libraries, only:[:create, :destroy]
    resource :story_comments, only:[:create]
  end
  resources :story_comments, only:[:destroy]
  resources :article_comments, only:[:destroy]
  resources :categories, only:[:show]
  resources :libraries, only:[:index, :create, :destroy]

  get 'users/:id/admin' => 'users#admin_show', as: 'admin_user'
  get 'admin/cmd' => 'users#admin_command', as: 'admin_cmd'
  get 'comments/' => 'users#admin_comments', as: 'admin_comments'
  patch 'users/d/:id' => 'users#unsubscribe', as: 'unsubscribe_user'
  patch 'articles/ow/:id' => 'article_histories#overwrite', as: 'overwrite_article'
  delete 'article_comments/:id/admin' => 'article_comments#destroy_from_admin_page', as: 'admin_destroies_article_comment'
  delete 'story_comments/:id/admin' => 'story_comments#destroy_from_admin_page', as: 'admin_destroies_story_comment'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :article_histories, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_many :story_comments, dependent: :destroy
  has_many :article_comments, dependent: :destroy
  has_many :libraries, dependent: :destroy
  has_many :visiteds, dependent: :destroy

  has_many :from_messages, class_name: "Message",foreign_key: "from_id", dependent: :destroy
  has_many :to_messages, class_name: "Message",foreign_key: "to_id", dependent: :destroy
  has_many :sent_messages, through: :from_messages, source: :from
  has_many :received_messages, through: :to_messages, source: :to

  validates :name, presence: true, length:{maximum: 20}
  validates :email, presence: true, length:{maximum: 50}
  validates :caption, length:{maximum: 140}

  attachment :image

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  def send_message(other_user, room_id, comment)
    from_messages.create!(to_id: other_user.id, room_id: room_id, comment: comment)
  end

  def message_room_id(first_user, second_user)
    first_id = first_user.id.to_i
    second_id = second_user.id.to_i
    if first_id < second_id
      "#{first_user.id}-#{second_user.id}"
    else
      "#{second_user.id}-#{first_user.id}"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_authority, only: [:update, :unsubscribe]
  before_action :auth_admin, only: [:index, :admin, :admin_show, :admin_comments]
  before_action :unsubscribed_user?

  def top
    @articles = Article.page(params[:page]).per(10)
    @stories = Story.order(:created_at).reverse_order.page(params[:page]).per(10)
    @visits = Story.find(Visited.group(:story_id).order('count(story_id) desc').limit(5).pluck(:story_id))
    return unless request.xhr?
    case params[:type]
    when 'article'
      render "/articles/article_list"
    when 'story'
      render "/stories/story_list"
    end
  end

  def about
  end

  def show
    @user = User.find(params[:id])
    # 管理者マイページは、管理者以外に表示させない
    if user_signed_in?
      if @user.admin && current_user.admin == false
        redirect_to root_path, alert: '許可されていないリクエストです。'
        return
      end
    else
      if @user.admin
        redirect_to root_path, alert: '許可されていないリクエストです。'
        return
      end
    end
    # 退会済みユーザーは表示させない
    if @user.deleted_user
      redirect_to root_path, alert: '退会済みのユーザーです。'
      return
    end
    @stories = @user.stories.order(:created_at).reverse_order.page(params[:page]).per(10)
    @libraries = @user.libraries.count
    @visiteds = @user.visiteds.reverse
  end

  def index
    @users = User.order(:created_at).reverse_order.page(params[:page]).per(50).search(params[:search])
  end

  def admin_show
    @user = User.find(params[:id])
    @story_comments = @user.story_comments.order(:created_at).reverse_order
    @article_comments = @user.article_comments.order(:created_at).reverse_order
  end

  def admin_comments
    @article_comments = ArticleComment.order(:created_at).reverse_order.page(params[:page]).per(50).search(params[:search])
    @story_comments = StoryComment.order(:created_at).reverse_order.page(params[:page]).per(50).search(params[:search])
    @admin_comment_page = true
  end

  def admin_command
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '利用者情報を更新しました。'
    else
      flash.now[:alert] = '利用者情報の更新に失敗しました。'
      render :show
    end
  end

  def unsubscribe
    @user = User.find(params[:id])
    @user.deleted_user = true
    @user.save
    if @user == current_user
      reset_session
      redirect_to root_path, alert: '退会しました。'
      return
    end
    redirect_to root_path
  end

  def unsubscribed_user?
    if user_signed_in?
      if current_user.deleted_user == true
        reset_session
        redirect_to root_path, alert: '退会済みのユーザーです。'
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image, :caption)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def same_user_or_admin?(user)
    if user_signed_in?
      if user == current_user
        true
      elsif current_user.admin == true
        true
      else
        false
      end
    else
      false
    end
  end

  def admin?
    if user_signed_in?
      if current_user.admin == true
        true
      else
        false
      end
    else
      false
    end
  end

end

app/views/users/about.html.erb
<div class="container" >
  <div class="row">
    <div id="content-left" class="content-area col-md-6 col-xs-12">
      <div class ="content-box">
        <h2 class="content-box-head">エラーの調べ方</h2>
        <div class="content-box-body position-center margin-expand">
          <h3>キーワードで検索しよう</h3>
          <p class="display-pc">
            画面上部にある検索欄を使ってみましょう。<br/>
            キーワードを入力してサーチアイコンをクリックすると<br/>
            左に関連するエラー記事、右にストーリーがそれぞれ表示されます。<br/>
            何も入力せずにサーチアイコンをクリックすると<br/>
            最新記事が表示されます。<br/>
          </p>
          <p class="display-tab">
            画面下部にある検索欄を使ってみましょう。<br/>
            キーワードを入力してサーチアイコンをクリックすると<br/>
            左に関連するエラー記事、右にストーリーがそれぞれ表示されます。<br/>
            何も入力せずにサーチアイコンをクリックすると<br/>
            最新記事が表示されます。<br/>
          </p>
          <p class="display-mobile">
            画面下部にある検索欄を使ってみましょう。
            キーワードを入力してサーチアイコンをタップすると
            ページ1にエラー記事、ページ2にストーリーがそれぞれ表示されます。
          </p>
          <h3>エラー記事やストーリーを追加しよう</h3>
          <p>
            ログインすると、エラー記事の追加や編集ができるだけでなく、
            あなた自身のストーリーを投稿できます。
          </p>
        </div>
      </div>
    </div>


    <div id="content-right" class="content-area col-md-6">
      <div class ="content-box">
        <h2 class ="content-box-head">LiBRORRE活用する</h2>
        <div class="content-box-body position-center margin-expand">
          <h3>マイライブラリを活用しよう</h3>
          <p class="display-pc displat-tab">
            気になったストーリーや、繰り返し読み返したいストーリーは<br/>
            「ライブラリに追加」ボタンで、マイライブラリに追加できます。<br/>
            画面上部にある「ライブラリ」をクリックすると<br/>
            ライブラリに追加したストーリーと、自分が作成したストーリーを<br/>
            一覧で閲覧することができます。
          </p>
          <p class="display-mobile">
            気になったストーリーや、繰り返し読み返したいストーリーは、
            「ライブラリに追加」ボタンで、マイライブラリに追加できます。
            画面上部にある「ライブラリ」をクリックすると、
            ページ1でライブラリに追加したストーリーを閲覧でき、
            ページ2で自分が作成したストーリーを確認することができます。
          </p>
          <h3>ストーリーについてトークしよう</h3>
          <p class="display-pc displat-tab">
            ログインすると、ストーリーについてトークすることができます。<br/>
            各ストーリーごとにトークルームが設けられ<br/>
            自由に議論したり、感想を伝えたりすることができます。<br/>
          </p>
          <p class="display-mobile">
            気になったストーリーや、繰り返し読み返したいストーリーは、
            「ライブラリに追加」ボタンで、マイライブラリに追加できます。
            画面上部にある「ライブラリ」をクリックすると、
            ページ1でライブラリに追加したストーリーを閲覧でき、
            ページ2で自分が作成したストーリーを確認することができます。
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/admin_command.html.erb
<div class="row">
  <div id="content-left" class="content-area col-md-12 col-xs-12">
    <div class ="content-box">
      <h2 class="content-box-head">
        ストーリーのデータ変換
      </h2>
      <div class="content-box-body">
        <p>ストーリーのコンテンツデータをマークダウン形式に変換します。<br/>
        変換を始める場合は、「ストーリーの変換」を押してください。</p>
      </div>

      <div class="content-box-foot">
        <%= link_to(convert_story_path) do %>
          <div class="btn btn-half">ストーリーの変換</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/admin_comments.html.erb
<div class="container" >
  <div class="row">
     <div id="content-left" class="content-area col-md-12">
      <div class ="content-box">
        <h2 class="content-box-head">ディスカッション/トーク</h2>
        <div class="content-box-body col-md-6 col-xs-6">
          <h4>- ディスカッション一覧</h4>
          <div id="article-comment-lists" class="user-admin-comments">
            <%= render partial: '/article_comments/comments', locals:{article_comments: @article_comments, admin_comment_page: @admin_comment_page} %>
          </div>
        </div>

        <div class="content-box-body col-md-6 col-xs-6">
          <h4>- トーク一覧</h4>
          <div id="story-comment-lists" class="user-admin-comments">
            <%= render partial: '/story_comments/comments', locals:{story_comments: @story_comments, admin_comment_page: @admin_comment_page} %>
          </div>
        </div>

        <div class="content-box-foot">
          <div id="comment-flash">
            <%= render partial: '/layouts/flash', locals:{flash: flash} %>
          </div>
          <%= form_tag(admin_comments_path, method: :get, class: 'content-box-search-form-area') do %>
            <div class="content-box-search-form">
              <%= text_field_tag :search, '', class: 'content-box-search-form-textfield', placeholder:'キーワードを入力してください' %>
              <%= button_tag(type: 'submit', class: 'content-box-search-form-btn') do %>
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/admin_show.html.erb
<div class="container" >
  <div class="row">
     <div id="content-left" class="content-area col-md-12">
      <div class ="content-box">
        <h2 class="content-box-head"><%= @user.name %>が投稿したディスカッション/トーク</h2>
        <div class="content-box-body col-md-6 col-xs-6">
          <h4>- ディスカッション一覧</h4>
          <div id="article-comment-lists" class="user-admin-comments">
            <%= render partial: '/article_comments/comments', locals:{article_comments: @article_comments} %>
          </div>
        </div>

        <div class="content-box-body col-md-6 col-xs-6">
          <h4>- トーク一覧</h4>
          <div id="story-comment-lists" class="user-admin-comments">
            <%= render partial: '/story_comments/comments', locals:{story_comments: @story_comments} %>
          </div>
        </div>

        <div class="content-box-foot">
          <div id="comment-flash">
            <%= render partial: '/layouts/flash', locals:{flash: flash} %>
          </div>
          <%= link_to(user_path(@user)) do %>
          <span class="btn">利用者情報へ戻る</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div id="content-left" class="content-area col-md-12 col-xs-12">
      <div class ="content-box">
        <h2 class="content-box-head">ユーザー一覧</h2>
        <div class="content-box-body">
          <%= form_tag(users_path, method: :get, class: 'content-box-search-form-area') do %>
            <div class="content-box-search-form">
              <%= text_field_tag :search, '', class: 'content-box-search-form-textfield', placeholder:'キーワードを入力してください' %>
              <%= button_tag(type: 'submit', class: 'content-box-search-form-btn') do %>
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
              <% end %>
            </div>
          <% end %>
          <table class="table">
            <tr>
              <th></th>
              <th>利用者名</th>
              <th>登録日</th>
            </tr>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <% if user.deleted_user == true %>
                    <span class="btn-danger">退会済</span>
                  <% end %>
                </td>
                <td><%= link_to user.name, user_path(user)%></td>
                <td><%= daytime_localize(user.created_at) %></td>
              </tr>
            <% end %>
          </table>
          <div class="content-box-foot">
            <%= paginate @users %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div id="content-left" class="content-area col-md-6 col-xs-12">
      <div id="main-content" class ="content-box">
        <h2 class="content-box-head user-info">利用者情報</h2>
        <div class="content-box-body user-info">
          <div>
            <%= attachment_image_tag @user, :image, fallback:"no_image.png", size: '200x200' %>
          </div>
          <h3><%= @user.name %></h3>
          <!-- 利用者本人か、管理者のみメールアドレス表示 -->
          <% if same_user_or_admin?(@user) %>
            <p><%= @user.email %></p>
          <% end %>
          <p>ライブラリ保存数：<%= @libraries %></p>
          <p><%= simple_format(@user.caption) %></p>
        </div>

        <!-- 利用者本人か、管理者のみ編集ボタン表示 -->
        <% if same_user_or_admin?(@user) %>
          <div class="content-box-foot position-center">
            <% if current_user.admin == true %>
              <div id="sub-content-show" class="btn btn-half">利用者情報の編集</div>
              <%= link_to(admin_user_path(@user)) do %>
                <div class="btn btn-half">利用者のコメント一覧</div>
              <% end %>
            <% else %>
              <div id="sub-content-show" class="btn btn-wide">利用者情報の編集</div>
            <% end %>
          </div>
        <% end %>
      </div>

      <% if same_user_or_admin?(@user) %>
      <!-- 編集ボタンクリック時に表示 -->
        <div id="sub-content" class ="content-box">
          <h2 class ="content-box-head user-edit">利用者情報の編集</h2>
          <%= form_for(@user) do |f| %>
            <div class="content-box-body">
              <h3><%= f.text_field :name, placeholder:"変更後の名前" %></h3>
              <p><%= f.text_field :email, placeholder:"変更後のメールアドレス" %></p>
              <p><%= f.text_area :caption, placeholder:"自己紹介", class: 'body-textarea-mini' %></p>
              <p>プロフィール画像：</p>
              <p><%= f.attachment_field :image %></p>
              <% if @user.deleted_user == false %>
                <%= link_to "利用者情報の削除", unsubscribe_user_path(@user), method: :patch, class:"btn btn-danger",data: { confirm: '削除後はログインできなくなります。本当に削除してもよろしいですか？' } %>
              <% end %>
            </div>
            <div class="content-box-foot position-center">
              <%= f.submit "更新", class:"btn btn-half" %>
              <span id="sub-content-hide" class="btn btn-half">更新のキャンセル</span>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div id="content-right" class="content-area col-md-6 col-xs-12">
      <div class ="content-box">
          <!-- ログイン時と未ログイン時で表示を分ける -->
          <% if user_signed_in? %>
            <!-- 自分自身の情報を閲覧している場合、最近閲覧したストーリーを表示 -->
            <% if @user == current_user %>
              <h2 class ="content-box-head user-history">最近閲覧したストーリー</h2>
              <div class="content-box-body user-history">
                <% @visiteds.each do |visited| %>
                  <div class="content-list clearfix">
                    <h4><%= link_to visited.story.title, story_path(visited.story) %> / <%= link_to visited.story.user.name, user_path(visited.story.user) %></h4>
                    <p>
                      <%= daytime_localize(visited.story.created_at) %>/
                      ライブラリ登録数：<%= visited.story.libraries.count %>
                    </p>
                  </div>
                <% end %>
              </div>
            <!-- 他人の情報を閲覧している場合、表示ユーザーが作成したストーリーを表示 -->
            <% else %>
              <h2 class ="content-box-head user-history">作成したストーリー</h2>
              <div id="stories" class="content-box-body user-history">
                <%= render '/stories/story_lists_wrapper', stories: @stories %>
              </div>
            <% end %>
          <!-- 未ログイン時、表示ユーザーが作成したストーリーを表示 -->
          <% else %>
            <h2 class ="content-box-head user-history">作成したストーリー</h2>
            <div class="content-box-body user-history">
              <%= render '/stories/story_lists_wrapper', stories: @stories %>
            </div>
          <% end %>
      </div>
    </div>

  </div>
</div>

app/views/users/top.html.erb
<div class="container" >
  <div class="row">
    <% if user_signed_in? %>

    <div id="content-left" class="content-area col-md-6 col-xs-12">
      <div class ="content-box top-guide">
        <h2 class="content-box-head">よく見られているストーリー</h2>
        <div class="content-box-body position-center">
          <%= render '/visits/visit_lists_wrapper', visits: @visits %>
        </div>
      </div>
    </div>

    <div id="content-right" class="content-area col-md-6">
      <div class ="content-box">
        <h2 class ="content-box-head">新着ストーリー</h2>
        <div class="content-box-body">
          <%= render '/stories/story_lists_wrapper', stories: @stories %>
        </div>
      </div>
    </div>

    <% else %>

    <div id="content-left" class="content-area col-md-6 col-xs-12">
      <div class ="content-box">
        <h2 class="content-box-head">LiBRORREへようこそ</h2>
        <div class="content-box-body position-center margin-expand">
          <h3>世界はエラーで出来ている。</h3>
          <p>問題発生を示すエラーメッセージ。<br/>
            そのエラーには原因があり、必ず解決策が存在します。<br/>
            LiBRORREは、エラーメッセージから解決策を探る<br/>
            助けになるために生まれた、エラー検索サイトです。</p>
          <h3>私たちはエラーで繋がっている。</h3>
          <p>
            あなたが目の当たりにするエラーメッセージを前に悩む人は<br/>
            きっとあなただけではありません。<br/>
            あなたがエラーを読み解いたプロセスを共有すれば<br/>
            それは、きっと誰かの助けになります。<br/>
            また、あなたがエラーに悩む時、誰かのプロセスを辿って<br/>
            問題を解決できるかもしれません。
          </p>
          <h4>LiBRORREをフルに使いましょう。</h4>
          <%= link_to(new_user_registration_path) do %>
            <div class="btn btn-wide">会　員　登　録</div>
          <% end %>

          <%= link_to(new_user_session_path) do %>
            <div class="btn btn-wide btn-sub">ロ　グ　イ　ン</div>
          <% end %>
        </div>
      </div>
    </div>

    <div id="content-right" class="content-area col-md-6">
      <div class ="content-box">
        <h2 class ="content-box-head">新着ストーリー</h2>
        <div class="content-box-body">
          <%= render '/stories/story_lists_wrapper', stories: @stories %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>