config/routes.rb
Rails.application.routes.draw do
  root 'users#top'
  get '/about' => 'users#about', as: 'about'
  get '/article/:id/histories' => 'article_histories#index', as: 'article_histories'
  get '/article_histories/:id' => 'article_histories#show', as: 'article_history'
  get '/stories/convert' => 'stories#markdown_convertion', as: 'convert_story'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only:[:show, :index, :edit, :update]
  resources :articles, only:[:show, :index, :new, :edit, :create, :update, :destroy] do
    resource :stories, only:[:new, :create, :destroy]
    resource :article_comments, only:[:create]
  end
  resources :stories, only:[:show, :new, :edit, :create, :update, :destroy] do
    resource :libraries, only:[:create, :destroy]
    resource :story_comments, only:[:create]
  end
  resources :story_comments, only:[:destroy]
  resources :article_comments, only:[:destroy]
  resources :categories, only:[:show]
  resources :libraries, only:[:index, :create, :destroy]

  get 'users/:id/admin' => 'users#admin_show', as: 'admin_user'
  get 'admin/cmd' => 'users#admin_command', as: 'admin_cmd'
  get 'comments/' => 'users#admin_comments', as: 'admin_comments'
  patch 'users/d/:id' => 'users#unsubscribe', as: 'unsubscribe_user'
  patch 'articles/ow/:id' => 'article_histories#overwrite', as: 'overwrite_article'
  delete 'article_comments/:id/admin' => 'article_comments#destroy_from_admin_page', as: 'admin_destroies_article_comment'
  delete 'story_comments/:id/admin' => 'story_comments#destroy_from_admin_page', as: 'admin_destroies_story_comment'
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <div id="flash" class=<%= "#{key}" %>>
      <%= value %>
    </div>
<% end %>

app/views/layouts/_post_comment.html.erb
<%= form_for([parent, parent_comment], remote: true) do |f| %>
  <%= f.text_area :comment, class:'foot-textarea' %>
  <%= f.submit '送信', data: { "disable-with": "送信しています..." }, class:'btn btn-comment-submit', id: 'comment-submit' %>
<% end %>

app/views/layouts/_validation_error.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |errmsg| %>
    <div class="alert alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">close</span>
      </button>
      <%= errmsg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiBRORRE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!-- フラッシュメッセージ -->
    <div id="flash-messages">
      <%= render partial: '/layouts/flash', locals:{flash: flash} %>
    </div>

  <!-- Ajaxローディング画面 -->
    <div id="loading">
      <div class="loading-pic"></div>    
    </div>

  <!-- コンテンツ部分 -->

    <header class="clearfix">
      <%= link_to(root_path) do %>
        <div class="header-logo">
          <%= image_tag asset_path('logo.png'), class:"header-logo-image" %>
        </div>
      <% end %>
      <div class="header-search clearfix">
        <%= form_tag(articles_path, method: :get, class: 'header-search-form-area') do %>
          <div class="header-search-form">
            <%= text_field_tag :search, '', class: 'header-search-form-textfield', placeholder:'エラーメッセージを入力' %>
            <%= button_tag(type: 'submit', class: 'header-search-form-btn') do %>
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            <% end %>
          </div>
        <% end %>
      </div>

      <% if admin? %>
      <div class="header-nav clearfix">
        <div class="header-nav-list">
          <%= link_to(users_path) do %>
            <p class="header-nav-text">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              ユーザー一覧
            </p>
          <% end %>
        </div>
        <div class="header-nav-list">
          <%= link_to(admin_comments_path) do %>
            <p class="header-nav-text">
              <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
              コメント検索
            </p>
          <% end %>
        </div>
        <div class="header-nav-list">
          <%= link_to(destroy_user_session_path, method: :delete) do %>
            <p class="header-nav-text">
              <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
              ログアウト
            </p>
          <% end %>
        </div>
      </div>

      <% elsif user_signed_in? %>

      <div class="header-nav clearfix">
        <div class="header-nav-list">
          <%= link_to(about_path) do %>
            <p class="header-nav-text">
              <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
              使い方
            </p>
          <% end %>
        </div>
        <div class="header-nav-list">
          <%= link_to(libraries_path) do %>
            <p class="header-nav-text">
              <span class="glyphicon glyphicon-book" aria-hidden="true"></span>ライブラリ
            </p>
          <% end %>
        </div>
        <div id="user-menu" class="header-nav-list">
          <ul class="header-nav-text">
            <li>
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              <%= current_user.name %> ▼
            </li>
            <ul id="user-menu-topics">
              <%= link_to(user_path(current_user)) do %>
                <li>利用者情報</li>
              <% end %>
              <%= link_to(destroy_user_session_path, method: :delete) do %>
                <li>ログアウト</li>
              <% end %>
            </ul>
          </ul>
        </div>
      </div>

      <% else %>

      <div class="header-nav clearfix">
        <div class="header-nav-list">
          <%= link_to(about_path) do %>
            <p class="header-nav-text">
              <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
              使い方
            </p>
          <% end %>
        </div>
        <div class="header-nav-list">
          <%= link_to(new_user_registration_path) do %>
            <p class="header-nav-text">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              登録
            </p>
          <% end %>
        </div>
        <div class="header-nav-list">
          <%= link_to(new_user_session_path) do %>
            <p class="header-nav-text">
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
              ログイン
            </p>
          <% end %>
        </div>
      </div>

      <% end %>

    </header>
    <%= yield %>

    <footer>
      <div class="footer-search clearfix">
        <%= form_tag(articles_path, method: :get, class: 'footer-search-form-area') do %>
          <div class="footer-search-form">
            <%= text_field_tag :search, '', class: 'footer-search-form-textfield', placeholder:'エラーメッセージを入力' %>
            <%= button_tag(type: 'submit', class: 'footer-search-form-btn') do %>
              <span class="glyphicon glyphicon-search footer-search-form-icon" aria-hidden="true"></span>
            <% end %>
          </div>
        <% end %>
      </div>
      ©️2019 Kazuki Kakuya
    </footer>

  </body>
</html>